import i1 from "../../../assets/table-data/table5.png";
import i2 from "../../../assets/icons/Etherium-icon.png";

export const tabledata = [
    {
        sno: 1,
        icon: i2,
        image: i1,
        name: "The Saudis ",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 2,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 3,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 4,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 5,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 6,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 7,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
    {
        sno: 8,
        icon: i2,
        image: i1,
        name: "The Saudis",
        price: "946.98",
        qty: "10",
        from: "Labmonk...",
        to: "Velocity",
        time: "20 Sec ago",
        items: "10.4k",
    },
];